// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using assignment4.data_access_folder;

namespace assignment4.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20200408211124_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("assignment4.Models.safetyratings", b =>
                {
                    b.Property<int>("veh_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ComplaintsCount");

                    b.Property<string>("FrontCrashDriversideRating");

                    b.Property<string>("FrontCrashPassengersideRating");

                    b.Property<string>("Make");

                    b.Property<string>("Model");

                    b.Property<int>("ModelYear");

                    b.Property<string>("OverallFrontCrashRating");

                    b.Property<string>("OverallRating");

                    b.Property<string>("OverallSideCrashRating");

                    b.Property<string>("RecallsCount");

                    b.Property<string>("RolloverPossibility");

                    b.Property<string>("RolloverRating");

                    b.Property<string>("SideCrashDriversideRating");

                    b.Property<string>("SideCrashPassengersideRating");

                    b.Property<string>("SidePoleCrashRating");

                    b.Property<string>("VehicleDescription");

                    b.Property<int>("VehicleId");

                    b.HasKey("veh_id");

                    b.ToTable("safety");
                });

            modelBuilder.Entity("assignment4.Models.v_id", b =>
                {
                    b.Property<int>("veh_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VehicleDescription");

                    b.Property<int>("VehicleId");

                    b.HasKey("veh_id");

                    b.ToTable("ids");
                });

            modelBuilder.Entity("assignment4.Models.v_make", b =>
                {
                    b.Property<int>("make_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Make");

                    b.Property<int>("ModelYear");

                    b.HasKey("make_id");

                    b.ToTable("makes");
                });

            modelBuilder.Entity("assignment4.Models.v_model", b =>
                {
                    b.Property<int>("model_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Make");

                    b.Property<string>("Model");

                    b.Property<int>("ModelYear");

                    b.HasKey("model_id");

                    b.ToTable("models");
                });

            modelBuilder.Entity("assignment4.Models.v_year", b =>
                {
                    b.Property<int>("year_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ModelYear");

                    b.HasKey("year_id");

                    b.ToTable("years");
                });
#pragma warning restore 612, 618
        }
    }
}
